server:
  port: 8102

spring:
  application:
    name: ms-order
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ms_order
    username: postgres
    password: admin

  jpa:
    open-in-view: false
    show-sql: true

  liquibase:
    change-log: classpath:liquibase/changelog-master.yml

ms-product-client:
  url: http://localhost:8101

ms-payment-client:
    url: http://localhost:8103